# Generated by Django 6.0.3 on 2026-03-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gatunek',
                'verbose_name_plural': 'Gatunki',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Platforma',
                'verbose_name_plural': 'Platformy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('producer', models.CharField(blank=True, max_length=150, verbose_name='Producent')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data premiery')),
                ('status', models.CharField(choices=[('planowana', 'Planowana'), ('dostepna', 'Dostępna'), ('ukonczona', 'Ukończona')], default='dostepna', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.genre', verbose_name='Gatunek')),
                ('platforms', models.ManyToManyField(blank=True, related_name='games', to='games.platform', verbose_name='Platformy')),
            ],
            options={
                'verbose_name': 'Gra',
                'verbose_name_plural': 'Gry',
                'ordering': ['title'],
                'constraints': [models.UniqueConstraint(fields=('genre', 'title'), name='uniq_game_title_in_genre')],
            },
        ),
    ]
