# Generated by Django 6.0.3 on 2026-04-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('game_url', models.URLField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=150)),
                ('developer', models.CharField(blank=True, max_length=150)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('freetogame_profile_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
